-- 1. Add TP/SL columns to trades table
ALTER TABLE trades ADD COLUMN IF NOT EXISTS stop_loss numeric;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS take_profit numeric;

-- 2. Create posts table for the Blog
CREATE TABLE IF NOT EXISTS posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
