-- Create logs table if it doesn't exist
CREATE TABLE IF NOT EXISTS logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null, -- 'INFO', 'ERROR', 'TRADE'
  message text not null,
  ai_response text, -- JSON string of full AI reasoning
  market_data jsonb -- Snapshot of price, funding, etc. at that moment
);

-- Enable Row Level Security
ALTER TABLE logs ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anyone (anon) to READ logs (Public transparency)
CREATE POLICY "Public can view logs"
ON logs FOR SELECT
TO anon, authenticated
USING (true);

-- Policy: Allow service_role (worker) to INSERT logs
-- Note: service_role bypasses RLS by default, but good to be explicit or if using a strictly scoped role.
-- If using standard supabase service key, this isn't strictly necessary for INSERT, 
-- but ensuring no regressions if we ever switch to authenticated users writing logs.
CREATE POLICY "Service role can insert logs"
ON logs FOR INSERT
TO service_role
WITH CHECK (true);

-- Optional: Clean up old logs (e.g., keep only last 7 days) via a cron job or manual trigger
-- (Not implemented here, but good practice)
